(function () {
  "use strict";
  const c = { fault: document.getElementById("ot-fault"), latency: document.getElementById("ot-latency"), loss: document.getElementById("ot-loss"), local: document.getElementById("ot-local") };
  const o = { latency: document.getElementById("ot-latency-value"), loss: document.getElementById("ot-loss-value"), owner: document.getElementById("ot-owner"), ownerDetail: document.getElementById("ot-owner-detail"), budget: document.getElementById("ot-budget"), budgetDetail: document.getElementById("ot-budget-detail"), action: document.getElementById("ot-action"), actionDetail: document.getElementById("ot-action-detail"), status: document.getElementById("ot-status"), plain: document.getElementById("ot-plain"), technical: document.getElementById("ot-technical"), budgetLane: document.getElementById("ot-budget-lane"), remoteLane: document.getElementById("ot-remote-lane") };
  const descriptions = { none: ["PPC/PCS local", "operación coordinada", "EMS optimiza", "los lazos críticos permanecen locales."], "ems-loss": ["PCS/PPC local", "última política segura", "Degradar con seguridad", "el despacho central se pierde; V/f y protección no."], "goose-loss": ["Protección local", "respaldo requerido", "Restringir o aislar", "una función asistida no debe convertirse en un punto único de falla."], "clock-loss": ["PCS/PPC local", "sincronismo inválido", "Bloquear synch-check", "las acciones que dependen de marca temporal común deben inhibirse."], "remote-compromise": ["PCS/PPC local", "canal remoto aislado", "Aislar acceso remoto", "la prioridad es preservar control local, logs y una ruta manual autorizada."] };
  function render() {
    const latency = Number(c.latency.value), loss = Number(c.loss.value), fault = c.fault.value, d = descriptions[fault];
    const effective = Math.round(latency * (1 + loss / 100));
    const risk = (fault === "goose-loss" && !c.local.checked) || (latency > 150 && fault !== "none");
    o.latency.value = `${latency} ms`; o.loss.value = `${loss} %`; o.owner.textContent = c.local.checked ? d[0] : "Dependencia remota"; o.ownerDetail.textContent = d[1]; o.budget.textContent = `${effective} ms`; o.budgetDetail.textContent = loss ? "degradado por pérdida" : "sin pérdida simulada"; o.action.textContent = risk ? "No seguro" : d[2]; o.actionDetail.textContent = risk ? "falta fallback local o el canal es demasiado lento" : "modo degradado definido";
    o.status.className = `stage-status ${risk ? "is-risk" : "is-good"}`; o.status.textContent = risk ? "Brecha de resiliencia" : "Fallback definido";
    o.plain.innerHTML = `<strong>En simple:</strong> ${d[3]}`; o.technical.innerHTML = `<strong>Lectura de ingeniería:</strong> latencia efectiva educativa = ${effective} ms; registrar jitter, pérdida, reloj, ownership de setpoints y transición de fallback <span class="evidence-tag">P</span>.`;
    document.querySelectorAll("[data-node]").forEach((node) => { const name = node.dataset.node; const inactive = (fault === "ems-loss" && name === "ems") || (fault === "remote-compromise" && name === "scada") || (fault === "goose-loss" && name === "ppc"); node.classList.toggle("is-active", !inactive); });
    o.budgetLane.classList.toggle("is-risk", fault === "ems-loss" || latency > 150); o.remoteLane.classList.toggle("is-risk", fault === "remote-compromise");
    window.GFMApp.update((s) => { s.activeModule = "11"; Object.assign(s.scenario.ot, { latencyMs: latency, packetLossPct: loss, linkFault: fault, localControllerAvailable: c.local.checked, clockHealthy: fault !== "clock-loss" }); return s; });
  }
  const s = window.GFMApp.getState(); c.fault.value = s.scenario.ot.linkFault || "none"; c.latency.value = s.scenario.ot.latencyMs; c.loss.value = s.scenario.ot.packetLossPct; c.local.checked = s.scenario.ot.localControllerAvailable; Object.values(c).forEach((el) => el.addEventListener("input", render)); window.GFMApp.markComplete("11"); render();
})();
